# -*- coding: utf-8 -*-
"""SQL Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4UTwnS7yYAfmzReDO1j4LtBEty5-VaE
"""

pip install -U transformers

#use a pipiline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

messages = [
    {"role": "user", "content": "Who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

pip install -q gradio transformers torch black autopep8 reportlab requests

!pip install -q gradio transformers torch black autopep8 reportlab requests sqlite3

# sql_query_generator.py
# Full reconstructed Python code based on the provided document

import re
import json
import sqlite3
from pathlib import Path
from datetime import datetime
import urllib.parse

import gradio as gr
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
import requests

# ============================================================
# DATABASE SCHEMA
# ============================================================
SCHEMA = {
    'users': {
        'id': 'INTEGER PRIMARY KEY',
        'name': 'TEXT',
        'email': 'TEXT',
        'signup_date': 'DATE',
        'age': 'INTEGER',
        'country': 'TEXT',
        'status': 'TEXT'
    },
    'orders': {
        'id': 'INTEGER PRIMARY KEY',
        'user_id': 'INTEGER',
        'product_name': 'TEXT',
        'amount': 'REAL',
        'order_date': 'DATE',
        'status': 'TEXT'
    },
    'products': {
        'id': 'INTEGER PRIMARY KEY',
        'name': 'TEXT',
        'price': 'REAL',
        'category': 'TEXT',
        'stock': 'INTEGER'
    },
    'transactions': {
        'id': 'INTEGER PRIMARY KEY',
        'user_id': 'INTEGER',
        'amount': 'REAL',
        'date': 'DATE',
        'type': 'TEXT'
    }
}

# ============================================================
# SECURITY & SQL GENERATION
# ============================================================
DANGEROUS_KEYWORDS = ['DROP', 'DELETE', 'ALTER', 'TRUNCATE', 'INSERT', 'UPDATE', 'EXEC', 'EXECUTE']
DANGEROUS_CHARS = [';', '--', '/*', '*/', 'xp_', 'sp_']

def is_safe(text: str) -> bool:
    """Check if text contains dangerous SQL keywords or characters."""
    if not isinstance(text, str):
        return False
    text_upper = text.upper()
    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text_upper:
            return False
    for char in DANGEROUS_CHARS:
        if char in text:
            return False
    return True

def get_table_name(query_text: str) -> str:
    """Intelligently infer table name from natural language."""
    query_lower = query_text.lower()
    keyword_map = {
        'users': ['user', 'users', 'customer', 'customers', 'account', 'accounts', 'profile'],
        'orders': ['order', 'orders', 'purchase', 'purchases', 'buy', 'bought'],
        'products': ['product', 'products', 'item', 'items', 'goods'],
        'transactions': ['transaction', 'transactions', 'payment', 'payments', 'transfer']
    }
    for table, keywords in keyword_map.items():
        for keyword in keywords:
            if keyword in query_lower:
                return table
    return 'users'  # Default table

def get_column_names(table_name: str, query_text: str):
    """Map natural language to actual column names."""
    query_lower = query_text.lower()
    columns = list(SCHEMA.get(table_name, {}).keys())
    selected_cols = []

    column_map = {
        'name': ['name', 'username', 'full name'],
        'email': ['email', 'mail', 'address'],
        'signup_date': ['signup', 'created', 'joined', 'registered', 'date', 'month'],
        'age': ['age', 'years'],
        'amount': ['amount', 'price', 'cost', 'total'],
        'date': ['date', 'when'],
        'status': ['status', 'state'],
        'country': ['country', 'location', 'place'],
        'product_name': ['product', 'product_name', 'item', 'items', 'name'],
        'price': ['price', 'cost'],
        'stock': ['stock', 'inventory']
    }

    for col, keywords in column_map.items():
        if col in columns:
            for keyword in keywords:
                if keyword in query_lower:
                    selected_cols.append(col)
                    break

    # If user explicitly asks for specific columns separated by commas, try to parse them
    explicit_cols = re.findall(r'\b(select|show|give|return)\s+([a-z0-9_,\s]+)\b', query_lower)
    if explicit_cols:
        # attempt to extract column names from the last match
        cols_text = explicit_cols[-1][1]
        for token in re.split(r'[,\s]+', cols_text):
            token = token.strip()
            if token in columns and token not in selected_cols:
                selected_cols.append(token)

    if not selected_cols:
        selected_cols = ['*']
    else:
        # preserve order and remove duplicates
        selected_cols = list(dict.fromkeys(selected_cols))
    return selected_cols

def extract_conditions(query_text: str):
    """Extract WHERE conditions from natural language."""
    query_lower = query_text.lower()
    conditions = []

    # Temporal conditions for signup_date or date fields
    if 'last month' in query_lower:
        # Use signup_date if present in schema; otherwise use date
        if 'signup_date' in SCHEMA.get('users', {}):
            conditions.append("DATE(signup_date) >= DATE('now', '-1 month')")
        else:
            conditions.append("DATE(date) >= DATE('now', '-1 month')")

    if 'last year' in query_lower or 'this year' in query_lower:
        if 'signup_date' in SCHEMA.get('users', {}):
            conditions.append("DATE(signup_date) >= DATE('now', '-1 year')")
        else:
            conditions.append("DATE(date) >= DATE('now', '-1 year')")

    if 'last week' in query_lower:
        if 'signup_date' in SCHEMA.get('users', {}):
            conditions.append("DATE(signup_date) >= DATE('now', '-7 days')")
        else:
            conditions.append("DATE(date) >= DATE('now', '-7 days')")

    if 'today' in query_lower:
        if 'signup_date' in SCHEMA.get('users', {}):
            conditions.append("DATE(signup_date) = DATE('now')")
        else:
            conditions.append("DATE(date) = DATE('now')")

    # Active/inactive status
    if 'active' in query_lower:
        conditions.append("status = 'active'")
    elif 'inactive' in query_lower:
        conditions.append("status = 'inactive'")

    # Amount filtering (greater than / less than)
    amount_match = re.search(r'(?:more than|greater than|above)\s+([0-9]+)', query_lower)
    if amount_match:
        conditions.append(f"amount > {amount_match.group(1)}")

    amount_match = re.search(r'(?:less than|below)\s+([0-9]+)', query_lower)
    if amount_match:
        conditions.append(f"amount < {amount_match.group(1)}")

    # Specific equality patterns like "where country is India"
    country_match = re.search(r'country\s+(?:is|=)\s+([A-Za-z0-9_\- ]+)', query_lower)
    if country_match:
        country_val = country_match.group(1).strip()
        conditions.append(f"country = '{country_val}'")

    return conditions

def generate_sql(query_text: str):
    """Generate SQLite SQL from natural language."""
    if not is_safe(query_text):
        return None, "X UNSAFE: Query contains dangerous SQL keywords or characters!"

    table = get_table_name(query_text)
    columns = get_column_names(table, query_text)
    columns_str = ', '.join(columns) if columns != ['*'] else '*'

    # Build base query
    sql = f"SELECT {columns_str} FROM {table}"

    # Add conditions
    conditions = extract_conditions(query_text)
    if conditions:
        sql += " WHERE " + " AND ".join(conditions)

    # Add limit unless user asked for all
    if 'all' not in query_text.lower():
        sql += " LIMIT 10"

    explanation = f"Generated from table '{table}' with columns: {columns_str}"
    return sql, explanation

# ============================================================
# Chat / History / Utilities
# ============================================================
query_history = []

def process_query(user_query: str, chat_history):
    """Process database query request and update chat history."""
    if not isinstance(user_query, str) or not user_query.strip():
        return chat_history

    chat_history.append((user_query, "Processing ..."))

    sql_query, explanation = generate_sql(user_query)

    if sql_query is None:
        response = f"X ERROR\n\n{explanation}"
    else:
        response = f"SQL GENERATED\n\n```sql\n{sql_query}\n```\n\n{explanation}"
        query_history.append({
            'user': user_query,
            'sql': sql_query,
            'timestamp': datetime.now().isoformat()
        })

    chat_history[-1] = (user_query, response)
    return chat_history

def clear_chat():
    global query_history
    query_history = []
    return []

# ============================================================
# Export / Sharing Functions
# ============================================================
def download_pdf():
    if not query_history:
        return "X No queries to export!", None

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"sql_queries_{timestamp}.pdf"

    try:
        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=colors.HexColor('#FF6B6B'),
            spaceAfter=20,
            alignment=1
        )
        story.append(Paragraph("SQL Query Report", title_style))
        story.append(Paragraph(f"Generated: {datetime.now()}", styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))

        for i, query in enumerate(query_history, 1):
            story.append(Paragraph(f"<b>Query #{i}</b>", styles['Heading2']))
            story.append(Paragraph(f"<b>User Request:</b> {query['user']}", styles['Normal']))
            story.append(Spacer(1, 0.05 * inch))
            story.append(Paragraph(f"<b>Generated SQL:</b>", styles['Normal']))
            # Use a monospaced style if desired; here we keep Normal but wrap in <pre> style via Paragraph
            sql_text = query['sql'].replace('<', '&lt;').replace('>', '&gt;')
            story.append(Paragraph(f"<font color='#4ECDC4'><code>{sql_text}</code></font>", styles['Code'] if 'Code' in styles else styles['Normal']))
            story.append(Spacer(1, 0.15 * inch))

        doc.build(story)
        return f"PDF Downloaded: {filename}", filename
    except Exception as e:
        return f"X Error: {str(e)}", None

def download_txt():
    if not query_history:
        return "X No queries to export!", None

    content = f"SQL Query History Report\nGenerated: {datetime.now()}\n{'='*60}\n\n"
    for i, query in enumerate(query_history, 1):
        content += f"Query #{i}\n"
        content += f"User Request: {query['user']}\n"
        content += f"Generated SQL: {query['sql']}\n"
        content += f"Timestamp: {query['timestamp']}\n"
        content += f"{'-'*60}\n\n"

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"sql_queries_{timestamp}.txt"

    try:
        Path(filename).write_text(content)
        return f"TXT Downloaded: {filename}", filename
    except Exception as e:
        return f"X Error: {str(e)}", None

def generate_whatsapp_link():
    if not query_history:
        return "X No queries to share!"

    message = "*SQL Queries Generated*\n\n"
    for i, query in enumerate(query_history[-5:], 1):
        message += f"*Query {i}:* {query['user']}\n"
        message += f"{query['sql']}\n\n"

    encoded_message = urllib.parse.quote(message)
    whatsapp_link = f"https://wa.me/?text={encoded_message}"
    return f"WhatsApp Link Created!\n\n{whatsapp_link}\n\nClick to open WhatsApp and share!"

def generate_facebook_link():
    if not query_history:
        return "X No queries to share!"

    message = "Check out these SQL queries I generated: "
    for query in query_history[-3:]:
        message += f"{query['user']} > {query['sql']} | "

    encoded_message = urllib.parse.quote(message)
    facebook_link = f"https://www.facebook.com/sharer/sharer.php?quote={encoded_message}"
    return f"Facebook Link Created!\n\n{facebook_link}\n\nClick to share on Facebook!"

# ============================================================
# Gradio Interface
# ============================================================
def build_ui():
    with gr.Blocks(title="SQL Query Generator", theme=gr.themes.Base()) as demo:
        gr.Markdown("# SQL Query Generator\n## Natural Language > SQLite SQL\nConvert plain English requests into safe, production-ready SQL queries!")

        with gr.Row():
            with gr.Column(scale=3):
                chatbot = gr.Chatbot(label="> Query Conversion", height=450, show_copy_button=True, bubble_full_width=False)
                query_input = gr.Textbox(label="Natural Language Request", placeholder="e.g., Show me all users who signed up last month", lines=2)
                send_btn = gr.Button("Generate SQL", variant="primary")
                send_btn.click(process_query, inputs=[query_input, chatbot], outputs=[chatbot])
                query_input.submit(process_query, inputs=[query_input, chatbot], outputs=[chatbot])

            with gr.Column(scale=1):
                gr.Markdown("### Controls")
                clear_btn = gr.Button("Clear History", variant="stop", size="sm")
                clear_btn.click(lambda: [], outputs=[chatbot])

                gr.Markdown("### Export")
                pdf_btn = gr.Button("Download PDF", size="sm", variant="primary")
                txt_btn = gr.Button("Download TXT", size="sm", variant="primary")
                pdf_file = gr.File(label="PDF File", visible=True)
                txt_file = gr.File(label="TXT File", visible=True)
                export_status = gr.Textbox(label="Status", interactive=False, lines=2)

                pdf_btn.click(download_pdf, outputs=[export_status, pdf_file])
                txt_btn.click(download_txt, outputs=[export_status, txt_file])

                gr.Markdown("---")
                gr.Markdown("### Share")
                whatsapp_btn = gr.Button("> WhatsApp", size="sm", variant="secondary")
                facebook_btn = gr.Button("& Facebook", size="sm", variant="secondary")
                share_output = gr.Textbox(label="Share Link", interactive=False, lines=5)

                whatsapp_btn.click(lambda: generate_whatsapp_link(), outputs=[share_output])
                facebook_btn.click(lambda: generate_facebook_link(), outputs=[share_output])

                gr.Markdown("---")
                gr.Markdown("### Schema Info\n**Tables:**\n- users\n- orders\n- products\n- transactions\n\n**Supported Requests:**\n- User queries (last month, etc)\n- Order lookups\n- Product searches\n- Transaction reports")

        return demo

if __name__ == "__main__":
    demo = build_ui()
    print("\nSQL Query Generator Ready!\n")
    demo.launch(share=True, show_error=True, show_api=False)